'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''
''  GestorNotifDAL.vb
''  Implementation of the Class GestorNotifDAL
''  Generated by Enterprise Architect
''  Created on:      21-jun.-2015 17:42:41
''  Original author: Javier
''  
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''  Modification history:
''  
''
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''



Option Explicit On
Option Strict On

Public Class GestorNotifDAL


    ''' 
    ''' <param name="cuerpo"></param>
    ''' <param name="asunto"></param>
    ''' <param name="mail"></param>
    Public Shared Sub enviarNotif(ByVal cuerpo As String, ByVal asunto As String, ByVal mail As String)

    End Sub


End Class ' GestorNotifDAL

