'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''
''  GestorRolesDAL.vb
''  Implementation of the Class GestorRolesDAL
''  Generated by Enterprise Architect
''  Created on:      21-jun.-2015 17:42:42
''  Original author: Javier
''  
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''  Modification history:
''  
''
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''



Imports BE


Public Class GestorRolesDAL


    ''' 
    ''' <param name="roles"></param>
    ''' <param name="usr"></param>
    Public Sub asignarRoles(ByVal roles As RolBE, ByVal usr As UsuarioBE)

    End Sub

    Public Function buscarRoles() As List(Of RolBE)
        buscarRoles = Nothing
    End Function

    ''' 
    ''' <param name="usr"></param>
    Public Shared Function getRoles(ByVal usr As UsuarioBE) As List(Of RolBE)
        Dim table As DataTable

        Dim repository As New AccesoSQLServer

        repository.crearComando("BUSCAR_ROLES_SP")
        repository.addParam("@usr", usr.id)

        table = New DataTable
        table = repository.executeSearchWithAdapter()
        If (table.Rows.Count <> 1) Then
        End If
        Dim listaRoles As New List(Of BE.RolBE)
        For Each pepe As DataRow In table.Rows
            Dim rol As New BE.RolBE
            rol.id = pepe.Item(0)
            rol.descripcion = pepe.Item(1)

            listaRoles.Add(rol)
        Next

        Return listaRoles
    End Function


End Class ' GestorRolesDAL

