'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''
''  GestorRolesDAL.vb
''  Implementation of the Class GestorRolesDAL
''  Generated by Enterprise Architect
''  Created on:      21-jun.-2015 17:42:42
''  Original author: Javier
''  
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''  Modification history:
''  
''
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''



Option Explicit On
Option Strict On

Imports BE


Public Class GestorRolesDAL


    ''' 
    ''' <param name="roles"></param>
    ''' <param name="usr"></param>
    Public Sub asignarRoles(ByVal roles As RolBE, ByVal usr As UsuarioBE)

    End Sub

    Public Function buscarRoles() As List(Of RolBE)
        buscarRoles = Nothing
    End Function

    ''' 
    ''' <param name="usr"></param>
    Public Function getRoles(ByVal usr As UsuarioBE) As List(Of RolBE)
        getRoles = Nothing
    End Function


End Class ' GestorRolesDAL

