'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''
''  GestorIdiomaDAL.vb
''  Implementation of the Class GestorIdiomaDAL
''  Generated by Enterprise Architect
''  Created on:      21-jun.-2015 17:42:41
''  Original author: Javier
''  
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''  Modification history:
''  
''
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''



Option Explicit On
Option Strict On

Imports BE


Public Class GestorIdiomaDAL


    ''' 
    ''' <param name="componentes"></param>
    ''' <param name="idioma"></param>
    Public Sub altaIdioma(ByVal componentes As ComponenteBE, ByVal idioma As String)

    End Sub

    Public Function buscarComponentes() As List(Of ComponenteBE)
        buscarComponentes = Nothing
    End Function

    Public Function buscarIdiomas() As List(Of IdiomaBE)
        buscarIdiomas = Nothing
    End Function

    ''' 
    ''' <param name="idioma"></param>
    Public Sub modificarIdioma(ByVal idioma As IdiomaBE)

    End Sub


End Class ' GestorIdiomaDAL

