'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''
''  GestorBitacoraDAL.vb
''  Implementation of the Class GestorBitacoraDAL
''  Generated by Enterprise Architect
''  Created on:      21-jun.-2015 17:42:41
''  Original author: Javier
''  
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''  Modification history:
''  
''
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''



Option Explicit On
Option Strict On

Imports BE


Public Class GestorBitacoraDAL


    ''' 
    ''' <param name="hasta"></param>
    ''' <param name="desde"></param>
    ''' <param name="usr"></param>
    ''' <param name="tipo"></param>
    Public Sub buscarBitacoras(ByVal hasta As DateTime, ByVal desde As DateTime, ByVal usr As UsuarioBE, ByVal tipo As TipoEventoBE)

    End Sub

    ''' 
    ''' <param name="evento"></param>
    ''' <param name="usuario"></param>
    ''' <param name="fecha"></param>
    Public Sub registrarEvento(ByVal evento As TipoEventoBE, ByVal usuario As UsuarioBE, ByVal fecha As DateTime)

    End Sub


End Class ' GestorBitacoraDAL

