'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''
''  GestorIdiomaDAL.vb
''  Implementation of the Class GestorIdiomaDAL
''  Generated by Enterprise Architect
''  Created on:      21-jun.-2015 17:42:41
''  Original author: Javier
''  
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''  Modification history:
''  
''
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''



Imports BE


Public Class GestorIdiomaDAL


    ''' 
    ''' <param name="componentes"></param>
    ''' <param name="idioma"></param>
    Public Shared Sub altaIdioma(ByVal componentes As ComponenteBE, ByVal idioma As String)

    End Sub

    Public Shared Function buscarComponentes() As List(Of ComponenteBE)
        buscarComponentes = Nothing
    End Function

    Public Shared Function buscarIdiomas() As List(Of IdiomaBE)
        Dim table As DataTable

        Dim repository As New AccesoSQLServer
        'Try
        repository.crearComando("LISTAR_IDIOMAS_SP")
        table = New DataTable
        table = repository.executeSearchWithAdapter()
        If (table.Rows.Count <> 1) Then
            'Throw New Excepciones.UsuarioNoEncontradoExcepcion
        End If
        Dim idiomas As New List(Of BE.IdiomaBE)
        For Each pepe As DataRow In table.Rows
            Dim idioma As New BE.IdiomaBE
            idioma.id = pepe.Item(0)
            idioma.descripcion = pepe.Item(1)
            idiomas.Add(idioma)
        Next

        Return idiomas
    End Function

    ''' 
    ''' <param name="idioma"></param>
    Public Shared Sub modificarIdioma(ByVal idioma As IdiomaBE)

    End Sub


End Class ' GestorIdiomaDAL

