'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''
''  GestorResguardoDAL.vb
''  Implementation of the Class GestorResguardoDAL
''  Generated by Enterprise Architect
''  Created on:      21-jun.-2015 17:42:42
''  Original author: Javier
''  
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''  Modification history:
''  
''
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''



Option Explicit On
Option Strict On

Imports BE


Public Class GestorResguardoDAL


    Public Function buscarBackups() As List(Of BackupBE)
        buscarBackups = Nothing
    End Function

    ''' 
    ''' <param name="nombre"></param>
    Public Sub realizarBackup(ByVal nombre As String)

    End Sub

    ''' 
    ''' <param name="backup"></param>
    Public Sub realizarRestore(ByVal backup As BackupBE)

    End Sub


End Class ' GestorResguardoDAL

