'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''
''  ProveedorDAL.vb
''  Implementation of the Class ProveedorDAL
''  Generated by Enterprise Architect
''  Created on:      21-jun.-2015 17:42:44
''  Original author: Javier
''  
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''  Modification history:
''  
''
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''



Option Explicit On
Option Strict On

Imports BE


Public Class ProveedorDAL


    ''' 
    ''' <param name="prov"></param>
    Public Shared Sub altaProveedor(ByVal prov As ProveedorBE)

    End Sub

    ''' 
    ''' <param name="prod"></param>
    ''' <param name="prov"></param>
    Public Shared Sub asociarProvProd(ByVal prod As ProductoBE, ByVal prov As ProveedorBE)

    End Sub

    ''' 
    ''' <param name="proveedor"></param>
    Public Shared Sub bajaProveedor(ByVal proveedor As ProveedorBE)

    End Sub

    ''' 
    ''' <param name="prov"></param>
    Public Shared Function buscarProveedor(ByVal prov As ProveedorBE) As List(Of ProveedorBE)
        buscarProveedor = Nothing
    End Function

    ''' 
    ''' <param name="prov"></param>
    Public Shared Function checkProvExist(ByVal prov As ProveedorBE) As Boolean
        checkProvExist = False
    End Function

    ''' 
    ''' <param name="prov"></param>
    Public Shared Function checkProvUtilizado(ByVal prov As ProveedorBE) As Boolean
        checkProvUtilizado = False
    End Function

    ''' 
    ''' <param name="proveedor"></param>
    Public Shared Sub modificarProveedor(ByVal proveedor As ProveedorBE)

    End Sub


End Class ' ProveedorDAL

