'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''
''  UsuarioDAL.vb
''  Implementation of the Class UsuarioDAL
''  Generated by Enterprise Architect
''  Created on:      21-jun.-2015 17:42:44
''  Original author: Javier
''  
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''  Modification history:
''  
''
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''



Option Explicit On
Option Strict On

Imports BE


Public Class UsuarioDAL


    ''' 
    ''' <param name="usr"></param>
    Public Shared Sub altaCliente(ByVal usr As UsuarioBE)

    End Sub

    ''' 
    ''' <param name="usr"></param>
    Public Shared Sub altaUsuario(ByVal usr As UsuarioBE)

    End Sub

    ''' 
    ''' <param name="tipo"></param>
    ''' <param name="usuario"></param>
    ''' <param name="mail"></param>
    Public Shared Function buscarUsuarios(ByVal tipo As TipoUsuarioBE, ByVal usuario As String, ByVal mail As String) As List(Of UsuarioBE)
        buscarUsuarios = Nothing
    End Function

    ''' 
    ''' <param name="mail"></param>
    Public Shared Sub checkMailValido(ByVal mail As String)

    End Sub

    ''' 
    ''' <param name="usr"></param>
    Public Shared Function checkUsuarioYaRegistrado(ByVal usr As UsuarioBE) As Boolean
        checkUsuarioYaRegistrado = False
    End Function

    ''' 
    ''' <param name="usr"></param>
    Public Shared Sub eliminarUsuario(ByVal usr As UsuarioBE)

    End Sub

    ''' 
    ''' <param name="pass"></param>
    ''' <param name="usr"></param>
    Public Shared Sub login(ByVal pass As String, ByVal usr As String)

    End Sub

    ''' 
    ''' <param name="usr"></param>
    Public Shared Sub modificarCliente(ByVal usr As UsuarioBE)

    End Sub

    ''' 
    ''' <param name="usr"></param>
    Public Shared Sub modificarUsuario(ByVal usr As UsuarioBE)

    End Sub

    ''' 
    ''' <param name="mail"></param>
    ''' <param name="usr"></param>
    Public Shared Sub solicitarContrasena(ByVal mail As String, ByVal usr As String)

    End Sub


End Class ' UsuarioDAL

