'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''
''  UsuarioDAL.vb
''  Implementation of the Class UsuarioDAL
''  Generated by Enterprise Architect
''  Created on:      21-jun.-2015 17:42:44
''  Original author: Javier
''  
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''  Modification history:
''  
''
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''




Imports BE


Public Class UsuarioDAL


    ''' 
    ''' <param name="usr"></param>
    Public Shared Sub altaCliente(ByVal usr As UsuarioBE)

    End Sub

    ''' 
    ''' <param name="usr"></param>
    Public Shared Sub altaUsuario(ByVal usr As UsuarioBE)

    End Sub

    ''' 
    ''' <param name="tipo"></param>
    ''' <param name="usuario"></param>
    ''' <param name="mail"></param>
    Public Shared Function buscarUsuarios(ByVal tipo As TipoUsuarioBE, ByVal usuario As String, ByVal mail As String) As List(Of UsuarioBE)
        buscarUsuarios = Nothing
    End Function

    ''' 
    ''' <param name="mail"></param>
    Public Shared Sub checkMailValido(ByVal mail As String)

    End Sub

    ''' 
    ''' <param name="usr"></param>
    Public Shared Function checkUsuarioYaRegistrado(ByVal usr As UsuarioBE) As Boolean
        checkUsuarioYaRegistrado = False
    End Function

    ''' 
    ''' <param name="usr"></param>
    Public Shared Sub eliminarUsuario(ByVal usr As UsuarioBE)

    End Sub

    ''' 
    ''' <param name="pass"></param>
    ''' <param name="usr"></param>
    Public Shared Function login(ByVal pass As String, ByVal usr As String) As UsuarioBE
        Dim table As DataTable

        Dim repository As New AccesoSQLServer
        'Try
        repository.crearComando("LOGIN_SP")
        repository.addParam("@usr", usr)
        repository.addParam("@pass", pass)
        table = New DataTable
        table = repository.executeSearchWithAdapter()
        If (table.Rows.Count <> 1) Then
        End If
        For Each pepe As DataRow In table.Rows
            Dim usuario As New BE.UsuarioBE
            usuario.id = pepe.Item(0)
            usuario.nombre = pepe.Item(1)
            usuario.apellido = pepe.Item(2)
            usuario.usuario = usr
            usuario.password = pass
            Dim idioma As New BE.IdiomaBE
            idioma.id = pepe.Item(3)
            usuario.idioma = idioma
            Return usuario
        Next

        Return Nothing
    End Function

    ''' 
    ''' <param name="usr"></param>
    Public Shared Sub modificarCliente(ByVal usr As UsuarioBE)

    End Sub

    ''' 
    ''' <param name="usr"></param>
    Public Shared Sub modificarUsuario(ByVal usr As UsuarioBE)

    End Sub

    ''' 
    ''' <param name="mail"></param>
    ''' <param name="usr"></param>
    Public Shared Sub solicitarContrasena(ByVal mail As String, ByVal usr As String)

    End Sub

    Shared Function buscarPermisos(rol As RolBE) As List(Of BE.ComponenteBE)
        Dim table As DataTable

        Dim repository As New AccesoSQLServer
        'Try
        repository.crearComando("BUSCAR_PERMISOS_SP")
        repository.addParam("@rol", rol.id)

        table = New DataTable
        table = repository.executeSearchWithAdapter()
        If (table.Rows.Count <> 1) Then
            'Throw New Excepciones.UsuarioNoEncontradoExcepcion
        End If
        Dim listaComponentes As New List(Of BE.ComponenteBE)
        For Each pepe As DataRow In table.Rows
            Dim componente As New BE.ComponenteBE
            componente.id = pepe.Item(0)
            componente.nombre = pepe.Item(1)
            componente.texto = pepe.Item(2)
            If Not IsDBNull(pepe.Item(3)) Then
                componente.pagina = pepe.Item(3)
            End If

            If Not IsDBNull(pepe.Item(4)) Then
                componente.padre = New ComponenteBE
                componente.padre.id = pepe.Item(4)
                componente.padre.texto = pepe.Item(5)
            End If
            If Not IsDBNull(pepe.Item(6)) Then
                componente.formulario = pepe.Item(6)
            End If

            listaComponentes.Add(componente)
        Next

        Return listaComponentes
    End Function


End Class ' UsuarioDAL

