'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''
''  Util.vb
''  Implementation of the Class Util
''  Generated by Enterprise Architect
''  Created on:      21-jun.-2015 17:42:58
''  Original author: Javier
''  
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''  Modification history:
''  
''
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''



Option Explicit On
Option Strict On

Public Class Util


    Public Function checkDigVerif() As Boolean
        checkDigVerif = False
    End Function

    ''' 
    ''' <param name="datoEnc"></param>
    Public Shared Function desencriptar(ByVal datoEnc As String) As String
        desencriptar = ""
    End Function

    ''' 
    ''' <param name="dato"></param>
    Public Shared Function encriptar(ByVal dato As String) As String
        encriptar = ""
    End Function

    Public Sub generarDigitosVerif()

    End Sub


End Class ' Util
