'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''
''  GestorNotifBLL.vb
''  Implementation of the Class GestorNotifBLL
''  Generated by Enterprise Architect
''  Created on:      21-jun.-2015 17:42:20
''  Original author: Javier
''  
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''  Modification history:
''  
''
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

Public Class GestorNotifBLL


    ''' 
    ''' <param name="mail"></param>
    ''' <param name="asunto"></param>
    ''' <param name="mensaje"></param>
    Public Shared Sub enviarNotif(ByVal mail As Single, ByVal asunto As String, ByVal mensaje As String)

    End Sub


End Class ' GestorNotifBLL
