'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''
''  GestorIdiomaBLL.vb
''  Implementation of the Class GestorIdiomaBLL
''  Generated by Enterprise Architect
''  Created on:      21-jun.-2015 17:42:19
''  Original author: Javier
''  
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''  Modification history:
''  
''
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

Imports BE


Public Class GestorIdiomaBLL

    Private Shared _comps As List(Of BE.IdiomaBE)

    ''' 
    ''' <param name="componentes"></param>
    ''' <param name="idioma"></param>
    Public Shared Sub altaIdioma(ByVal componentes As ComponenteBE, ByVal idioma As String)

    End Sub

    Public Shared Function buscarComponentes() As List(Of ComponenteBE)
        buscarComponentes = Nothing
    End Function

    Public Shared Function buscarComponentes(ByVal idioma As BE.IdiomaBE) As List(Of ComponenteBE)
        For Each id As BE.IdiomaBE In getComponentesIdiomaticos()
            If id.id = idioma.id Then
                Return id.componentes
            End If
        Next
        Dim nuevoIdioma = New BE.IdiomaBE
        nuevoIdioma.id = idioma.id
        nuevoIdioma.componentes = DAL.GestorIdiomaDAL.buscarComponentes(nuevoIdioma)
        _comps.Add(nuevoIdioma)
        Return nuevoIdioma.componentes
    End Function

    Public Shared Function buscarIdiomas() As List(Of IdiomaBE)
        Return DAL.GestorIdiomaDAL.buscarIdiomas
    End Function

    ''' 
    ''' <param name="idioma"></param>
    Public Shared Sub modificarIdioma(ByVal idioma As IdiomaBE)

    End Sub

    Shared Function getTranslation(p1 As String, p2 As Integer) As String
        Return DAL.GestorIdiomaDAL.getTranslation(p1, p2)
    End Function

    Shared Function getComponentesIdiomaticos()
        If _comps Is Nothing Then
            _comps = New List(Of IdiomaBE)
        End If
        Return _comps
    End Function

End Class ' GestorIdiomaBLL
