'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''
''  GestorIdiomaBLL.vb
''  Implementation of the Class GestorIdiomaBLL
''  Generated by Enterprise Architect
''  Created on:      21-jun.-2015 17:42:19
''  Original author: Javier
''  
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''  Modification history:
''  
''
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''



Option Explicit On
Option Strict On

Imports BE


Public Class GestorIdiomaBLL


    ''' 
    ''' <param name="componentes"></param>
    ''' <param name="idioma"></param>
    Public Shared Sub altaIdioma(ByVal componentes As ComponenteBE, ByVal idioma As String)

    End Sub

    Public Shared Function buscarComponentes() As List(Of ComponenteBE)
        buscarComponentes = Nothing
    End Function

    Public Shared Function buscarComponentes(ByVal idioma As BE.IdiomaBE) As List(Of ComponenteBE)
        Return DAL.GestorIdiomaDAL.buscarComponentes(idioma)
    End Function

    Public Shared Function buscarIdiomas() As List(Of IdiomaBE)
        Return DAL.GestorIdiomaDAL.buscarIdiomas
    End Function

    ''' 
    ''' <param name="idioma"></param>
    Public Shared Sub modificarIdioma(ByVal idioma As IdiomaBE)

    End Sub

    Shared Function getTranslation(p1 As String, p2 As Integer) As String
        Return DAL.GestorIdiomaDAL.getTranslation(p1, p2)
    End Function


End Class ' GestorIdiomaBLL
