'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''
''  GestorBitacoraBLL.vb
''  Implementation of the Class GestorBitacoraBLL
''  Generated by Enterprise Architect
''  Created on:      21-jun.-2015 17:42:18
''  Original author: Javier
''  
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''  Modification history:
''  
''
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''



Imports BE


Public Class GestorBitacoraBLL

    Public Shared Function buscarBitacoras(ByVal fechahasta As DateTime, ByVal fechadesde As DateTime, ByVal tipo As BE.TipoEventoBE, ByVal usr As BE.UsuarioBE) As List(Of EventoBE)
        buscarBitacoras = Nothing
    End Function

    Public Shared Sub registrarEvento(ByVal usuario As UsuarioBE, ByVal tipo As Integer)
        DAL.GestorBitacoraDAL.registrarEvento(usuario, tipo)
    End Sub


End Class ' GestorBitacoraBLL

