'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''
''  ProveedorBLL.vb
''  Implementation of the Class ProveedorBLL
''  Generated by Enterprise Architect
''  Created on:      21-jun.-2015 17:42:23
''  Original author: Javier
''  
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''  Modification history:
''  
''
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''



Option Explicit On
Option Strict On

Imports BE


Public Class ProveedorBLL


    ''' 
    ''' <param name="prov"></param>
    Public Shared Sub altaProveedor(ByVal prov As ProveedorBE)

    End Sub

    ''' 
    ''' <param name="proveedor"></param>
    Public Shared Sub bajaProveedor(ByVal proveedor As ProveedorBE)

    End Sub

    ''' 
    ''' <param name="prov"></param>
    Public Shared Function buscarProveedores(ByVal prov As ProveedorBE) As List(Of ProveedorBE)
        buscarProveedores = Nothing
    End Function

    ''' 
    ''' <param name="proveedor"></param>
    Public Shared Sub modifcarProveedor(ByVal proveedor As ProveedorBE)

    End Sub


End Class ' ProveedorBLL
