'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''
''  UsuarioBLL.vb
''  Implementation of the Class UsuarioBLL
''  Generated by Enterprise Architect
''  Created on:      21-jun.-2015 17:42:24
''  Original author: Javier
''  
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''  Modification history:
''  
''
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

Imports BE


Public Class UsuarioBLL


    ''' 
    ''' <param name="usr"></param>
    Public Shared Function altaCliente(ByVal usr As UsuarioBE)
        usr.id = DAL.UsuarioDAL.altaCliente(usr)
        usr.domicilio.id = DAL.UsuarioDAL.altaDomicilio(usr)
        usr.telefono.id = DAL.UsuarioDAL.altaTelefono(usr)
        Util.Mailer.sendMail(usr.mail, "Alta de Usuario en el sistema", "Bienvenido/a" + usr.usuario + " ya puede empezar a operar con Muebla")
        Return usr
    End Function

    ''' 
    ''' <param name="usr"></param>
    Public Shared Sub altaUsuario(ByVal usr As UsuarioBE)

    End Sub

    ''' 
    ''' <param name="usuario"></param>
    ''' <param name="tipo"></param>
    ''' <param name="mail"></param>
    Public Shared Function buscarUsuarios(ByVal usuario As String, ByVal tipo As Int16, ByVal mail As String) As List(Of BE.UsuarioBE)
        Return DAL.UsuarioDAL.buscarUsuarios(tipo, usuario, mail)
    End Function

    ''' 
    ''' <param name="usr"></param>
    Public Shared Sub eliminarUsuario(ByVal usr As UsuarioBE)

    End Sub

    ''' 
    ''' <param name="pass"></param>
    ''' <param name="usr"></param>
    Public Shared Function login(ByVal pass As String, ByVal usr As String) As UsuarioBE
        Dim user As BE.UsuarioBE
        user = DAL.UsuarioDAL.login(pass, usr)
        If Not user Is Nothing Then
            user.roles = BLL.GestorRolesBLL.getRoles(user)
            For Each rol As BE.RolBE In user.roles
                rol.componentes = DAL.UsuarioDAL.buscarPermisos(rol)
            Next
            user.idioma.componentes = BLL.GestorIdiomaBLL.buscarComponentes(user.idioma)
            BLL.GestorBitacoraBLL.registrarEvento(user, Util.Enumeradores.Bitacora.LogueoExitoso)
        End If
        Return user
    End Function

    ''' 
    ''' <param name="usr"></param>
    Public Shared Sub modificarCliente(ByVal usr As UsuarioBE)

    End Sub

    ''' 
    ''' <param name="usr"></param>
    Public Shared Sub modificarUsuario(ByVal usr As UsuarioBE)

    End Sub

    ''' 
    ''' <param name="mail"></param>
    ''' <param name="usuario"></param>
    Public Shared Function solicitarContraseña(ByVal mail As String, ByVal usuario As String) As String
        Dim pass As String = DAL.UsuarioDAL.solicitarContrasena(mail, usuario)
        If Not pass Is Nothing Then
            Util.Mailer.sendMail(mail, "Recuperar Contrasena Muebla", "Usuario su mail es " + pass)
        End If
        Return pass
    End Function

    Shared Function getTiposUsuarios() As List(Of BE.TipoUsuarioBE)
        Return DAL.UsuarioDAL.getTiposUsuarios()
    End Function

    Shared Function getTiposDocumentos() As List(Of BE.TipoDocumentoBE)
        Return DAL.UsuarioDAL.getTiposDocumentos
    End Function

    Shared Function getProvincias() As List(Of BE.ProvinciaBE)
        Return DAL.UsuarioDAL.getProvincias
    End Function

    Shared Function getTiposLocalidades(p1 As Integer) As Object
        Return DAL.UsuarioDAL.getLocalidades(p1)
    End Function


End Class ' UsuarioBLL
