'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''
''  BackupBE.vb
''  Implementation of the Class BackupBE
''  Generated by Enterprise Architect
''  Created on:      21-jun.-2015 17:41:42
''  Original author: Javier
''  
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''  Modification history:
''  
''
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''



Option Explicit On
Option Strict On

Public Class BackupBE


    Private desc As String
    Private _fecha As DateTime
    Private _id As Long

    Public Property descripcion() As String
        Get
            Return desc
        End Get
        Set(ByVal Value As String)
            desc = Value
        End Set
    End Property

    Public Property fecha() As DateTime
        Get
            Return _fecha
        End Get
        Set(ByVal Value As DateTime)
            _fecha = Value
        End Set
    End Property

    Public Property id() As Long
        Get
            Return _id
        End Get
        Set(ByVal Value As Long)
            _id = Value
        End Set
    End Property



End Class ' BackupBE

