'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''
''  ComponenteBE.vb
''  Implementation of the Class ComponenteBE
''  Generated by Enterprise Architect
''  Created on:      21-jun.-2015 17:41:42
''  Original author: Javier
''  
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''  Modification history:
''  
''
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''



Option Explicit On
Option Strict On

Public Class ComponenteBE


    Private _id As Long
    Private _nombre As String
    Private _texto As String

    Public Property id() As Long
        Get
            Return _id
        End Get
        Set(ByVal Value As Long)
            _id = Value
        End Set
    End Property

		

    Public Property nombre() As String
        Get
            Return _nombre
        End Get
        Set(ByVal Value As String)
            _nombre = Value
        End Set
    End Property

    Public Property texto() As String
        Get
            Return _texto
        End Get
        Set(ByVal Value As String)
            _texto = Value
        End Set
    End Property


End Class ' ComponenteBE
