'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''
''  ComponenteBE.vb
''  Implementation of the Class ComponenteBE
''  Generated by Enterprise Architect
''  Created on:      21-jun.-2015 17:41:42
''  Original author: Javier
''  
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''  Modification history:
''  
''
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''



Public Class ComponenteBE


    Private _id As Long
    Private _nombre As String
    Private _texto As String
    Private _padre As BE.ComponenteBE
    Private _pagina As String
    Private _formulario As String

    Public Property formulario() As String
        Get
            Return _formulario
        End Get
        Set(ByVal value As String)
            _formulario = value
        End Set
    End Property


    Public Property pagina() As String
        Get
            Return _pagina
        End Get
        Set(ByVal value As String)
            _pagina = value
        End Set
    End Property


    Public Property padre() As BE.ComponenteBE
        Get
            Return _padre
        End Get
        Set(ByVal value As BE.ComponenteBE)
            _padre = value
        End Set
    End Property

    Public Property id() As Long
        Get
            Return _id
        End Get
        Set(ByVal Value As Long)
            _id = Value
        End Set
    End Property

		

    Public Property nombre() As String
        Get
            Return _nombre
        End Get
        Set(ByVal Value As String)
            _nombre = Value
        End Set
    End Property

    Public Property texto() As String
        Get
            Return _texto
        End Get
        Set(ByVal Value As String)
            _texto = Value
        End Set
    End Property


End Class ' ComponenteBE
