'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''
''  DomicilioBE.vb
''  Implementation of the Class DomicilioBE
''  Generated by Enterprise Architect
''  Created on:      21-jun.-2015 17:41:43
''  Original author: Javier
''  
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''  Modification history:
''  
''
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''



Option Explicit On
Option Strict On


Public Class DomicilioBE


    Private _calle As String
    Private _dpto As String
    Private _id As Long
    Private _localidad As LocalidadBE
    Private _numero As Long
    Private _piso As String
    Public m_LocalidadBE As LocalidadBE

    Public Property calle() As String
        Get
            Return _calle
        End Get
        Set(ByVal Value As String)
            _calle = Value
        End Set
    End Property

    Public Property dpto() As String
        Get
            Return _dpto
        End Get
        Set(ByVal Value As String)
            _dpto = Value
        End Set
    End Property

    Public Property id() As Long
        Get
            Return _id
        End Get
        Set(ByVal Value As Long)
            _id = Value
        End Set
    End Property


    Public Property numero() As Long
        Get
            Return _numero
        End Get
        Set(ByVal Value As Long)
            _numero = Value
        End Set
    End Property

    Public Property piso() As String
        Get
            Return _piso
        End Get
        Set(ByVal Value As String)
            _piso = Value
        End Set
    End Property


End Class ' DomicilioBE
