'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''
''  ProductoBE.vb
''  Implementation of the Class ProductoBE
''  Generated by Enterprise Architect
''  Created on:      21-jun.-2015 17:41:48
''  Original author: Javier
''  
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''  Modification history:
''  
''
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''



Option Explicit On
Option Strict On


Public Class ProductoBE


    Private _baja As Boolean
    Private _descripcion As String
    Private _id As Long
    Private _image1 As Object
    Private _image2 As Object
    Private _productos As ProductoBE
    Private _proveedores As ProveedorBE
    Private _tipoProducto As TipoProductoBE
    Public m_TipoProductoBE As TipoProductoBE
    Public m_ProveedorBE As ProveedorBE
    Public m_ProductoBE As ProductoBE

    Public Property descripcion() As String
        Get
            Return _descripcion
        End Get
        Set(ByVal Value As String)
            _descripcion = Value
        End Set
    End Property

    Public Property id() As Long
        Get
            Return _id
        End Get
        Set(ByVal Value As Long)
            _id = Value
        End Set
    End Property

    Public Property image1() As Object
        Get
            Return _image1
        End Get
        Set(ByVal Value As Object)
            _image1 = Value
        End Set
    End Property

    Public ReadOnly Property image2() As Object
        Get
            Return _image2
        End Get
    End Property


    Public Property productos() As ProductoBE
        Get
            Return _productos
        End Get
        Set(ByVal Value As ProductoBE)
            _productos = Value
        End Set
    End Property

    Public Property proveedores() As ProveedorBE
        Get
            Return _proveedores
        End Get
        Set(ByVal Value As ProveedorBE)
            _proveedores = Value
        End Set
    End Property

    Public Property tipoProducto() As TipoProductoBE
        Get
            Return _tipoProducto
        End Get
        Set(ByVal Value As TipoProductoBE)
            _tipoProducto = Value
        End Set
    End Property


End Class ' ProductoBE
