'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''
''  PromocionBE.vb
''  Implementation of the Class PromocionBE
''  Generated by Enterprise Architect
''  Created on:      21-jun.-2015 17:41:48
''  Original author: Javier
''  
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''  Modification history:
''  
''
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''



Option Explicit On
Option Strict On


Public Class PromocionBE



End Class ' PromocionBE

