'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''
''  UsuarioBE.vb
''  Implementation of the Class UsuarioBE
''  Generated by Enterprise Architect
''  Created on:      21-jun.-2015 17:41:53
''  Original author: Javier
''  
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''  Modification history:
''  
''
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''



Option Explicit On
Option Strict On


Public Class UsuarioBE

    Private _id As Integer
    Private _apellido As String
    Private _baja As Boolean
    Private _bloqueado As Boolean
    Private _cuil As Long
    Private _dni As Long
    Private _domicilio As DomicilioBE
    Private _idioma As IdiomaBE
    Private _roles As List(Of RolBE)
    Private _mail As String
    Private _nombre As String
    Private _password As String
    Private _telefono As TelefonoBE
    Private _tipoUsuario As TipoUsuarioBE
    Private _usuario As String
    Public m_RolBE As RolBE
    Public m_DomicilioBE As DomicilioBE
    Public m_TelefonoBE As TelefonoBE
    Public m_IdiomaBE As IdiomaBE
    Public m_TipoUsuarioBE As TipoUsuarioBE


    Public Property id() As Integer
        Get
            Return _id
        End Get
        Set(ByVal value As Integer)
            _id = value
        End Set
    End Property

    Public Property apellido() As String
        Get
            Return _apellido
        End Get
        Set(ByVal Value As String)
            _apellido = Value
        End Set
    End Property

    Public Property bloqueado() As Boolean
        Get
            Return _bloqueado
        End Get
        Set(ByVal Value As Boolean)
            _bloqueado = Value
        End Set
    End Property

    Public Property dni() As Long
        Get
            Return _dni
        End Get
        Set(ByVal Value As Long)
            _dni = Value
        End Set
    End Property

    Public Property domicilio() As DomicilioBE
        Get
            Return _domicilio
        End Get
        Set(ByVal Value As DomicilioBE)
            _domicilio = Value
        End Set
    End Property

    Public Property idioma() As IdiomaBE
        Get
            Return _idioma
        End Get
        Set(ByVal Value As IdiomaBE)
            _idioma = Value
        End Set
    End Property

    Public Property roles As List(Of RolBE)
        Get
            Return _roles
        End Get
        Set(ByVal Value As List(Of RolBE))
            _roles = Value
        End Set
    End Property

    Public Property mail() As String
        Get
            Return _mail
        End Get
        Set(ByVal Value As String)
            _mail = Value
        End Set
    End Property


    Public Property nombre() As String
        Get
            Return _nombre
        End Get
        Set(ByVal Value As String)
            _nombre = Value
        End Set
    End Property

    Public Property password() As String
        Get
            Return _password
        End Get
        Set(ByVal Value As String)
            _password = Value
        End Set
    End Property

    Public Property telefono() As TelefonoBE
        Get
            Return _telefono
        End Get
        Set(ByVal Value As TelefonoBE)
            _telefono = Value
        End Set
    End Property

    Public Property tipoUsuario() As TipoUsuarioBE
        Get
            Return _tipoUsuario
        End Get
        Set(ByVal Value As TipoUsuarioBE)
            _tipoUsuario = Value
        End Set
    End Property

    Public Property usuario() As String
        Get
            Return _usuario
        End Get
        Set(ByVal Value As String)
            _usuario = Value
        End Set
    End Property


End Class ' UsuarioBE
